### PR TITLE
improve cross-platform compilation

### PR DESCRIPTION
**Pull request by Jan200101**
- allow targeting systems other than the current one
- allow specifying other toolchains for the compile process
- recapitalize includes to work on case sensitive file systems

sdl2-config should probably be put into its own variable that can be specified at build-time to help with some troublesome toolchains but that is something that can be done at a later point

### CODE REVIEW

**Comment by nadiaholmquist** [comment]
Another issue for cross-platform building is that `00_sound_player.s` doesn't build properly when building on an ARM host, giving the following error:

```
as -I include -I build/us_pc --defsym VERSION_US=1 -MD build/us_pc/sound/sequences/00_sound_player.d -o build/us_pc/sound/sequences/00_sound_player.o sound/sequences/00_sound_player.s
sound/sequences/00_sound_player.s: Assembler messages:
sound/sequences/00_sound_player.s:87: Error: too many positional arguments
sound/sequences/00_sound_player.s:88: Error: too many positional arguments
sound/sequences/00_sound_player.s:89: Error: too many positional arguments
sound/sequences/00_sound_player.s:92: Error: too many positional arguments
sound/sequences/00_sound_player.s:93: Error: too many positional arguments
sound/sequences/00_sound_player.s:194: Error: too many positional arguments
sound/sequences/00_sound_player.s:195: Error: too many positional arguments
sound/sequences/00_sound_player.s:197: Error: too many positional arguments
sound/sequences/00_sound_player.s:200: Error: too many positional arguments
sound/sequences/00_sound_player.s:202: Error: too many positional arguments
sound/sequences/00_sound_player.s:225: Error: too many positional arguments
sound/sequences/00_sound_player.s:225: Error: unknown mnemonic `restore' -- `restore the value'
sound/sequences/00_sound_player.s:227: Error: too many positional arguments
sound/sequences/00_sound_player.s:228: Error: too many positional arguments
```

**Comment by Jan200101** [comment]
I don't know a good fix for getting rid of those assembler errors without getting rid of all the comments

**Comment by AaronDewes** [comment]
Replacing # with @ should work, but I'm not sure

**Comment by mkst** [comment]
> I don't know a good fix for getting rid of those assembler errors without getting rid of all the comments

Looking at the [3DS port code](https://github.com/sm64-port/sm64_3ds/blob/master/sound/sequences/00_sound_player.s#L88), you should use `/* these comments */` rather than `# these comments`.

**Comment by aboood40091** [comment]
> Actually, `as`, `cpp`, `objdump` and `objcopy` do not need to be cross compiled. They are just used to create binary data that will later be transformed to hex and be used in C source.

I disagree. You can't guarantee the user has those binaries without the prefix and you shouldn't force them to get them when they already have the ones with the prefix.

**Comment by Jan200101** [comment]
I've trashed the branch by accident while working on another PR, I've remade it to the best of my ability

> > I don't know a good fix for getting rid of those assembler errors without getting rid of all the comments
> 
> Looking at the [3DS port code](https://github.com/sm64-port/sm64_3ds/blob/master/sound/sequences/00_sound_player.s#L88), you should use `/* these comments */` rather than `# these comments`.

/* comments */ do not work with x86_64 GNU
```
sound/sequences/00_sound_player.s:993: Error: junk at end of line, first unrecognized character is `*'
```




> > Actually, `as`, `cpp`, `objdump` and `objcopy` do not need to be cross compiled. They are just used to create binary data that will later be transformed to hex and be used in C source.
> 
> I disagree. You can't guarantee the user has those binaries without the prefix and you shouldn't force them to get them when they already have the ones with the prefix.

this was my initial reasoning for it, as the comment that took issue with this was removed it was readded

**Pull request closed without merging**
