### PR TITLE
Fix "Error: too many positional arguments" when compiling on arm

### PR DESCRIPTION
**Pull request by patrickmollohan**
As the title explains, when compiling on arm devices, the inline comments cause errors, resulting in the build failing.

### CODE REVIEW

**Comment by runlevel5** [comment]
Is it for arm64 arch?

**Comment by patrickmollohan** [comment]
My apologies, should have specified. Yes, for arm64. More specifically, when compiling on my PinePhone running Mobian.

**Comment by alosrafas1213** [comment]
Did you fix the errors?
I had the same errors on a raspberry pi 4 and I fixed it by deleting the comments on the lines mentioned by the error

**Comment by MegaMech** [comment]
arm64 is not supported.
Have a great day!

**Comment by patrickmollohan** [comment]
@MegaMech um...you might want to reread? This isn't a help request; I fixed your shit. See where it says +26 -13?

**Comment by MegaMech** [comment]
Hi Patrick,

Thank you for the correction. Your request was reconsidered. Unfortunately, supporting arm64 is not within the scope of this repository. While this small change on the surface may seem like an obvious PR to accept it cannot be merged if it breaks compiling on supported systems. This issue appears to share relevancy with the main sm64 decomp (decomp/sm64) and not to sm64-port. A differing approach that fixes this issue may be in the works.

Have a great day!

**Pull request closed without merging**
