### PR TITLE
Optimize CFLAGS.

### PR DESCRIPTION
**Pull request by V10lator**

### CODE REVIEW

**Comment by mkst** [comment]
Have you tried this when compiling under windows via msys2? I applied the changes to the 3ds port and someone had issues compiling...

**Comment by V10lator** [comment]
No, I didn't try with msys2. Before I do that: What's the issue the user is facing (build log) ?

**Comment by mkst** [comment]
Just installed msys2 to make sure it wasn't user error. building from master was fine, deleted build/, applied this patch, and it craps out *right* at the end with:

```
lto-wrapper.exe: fatal error: make returned 2 exit status
compilation terminated.
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:821: build/us_pc/sm64.us.f3dex2e.exe] Error 1
```

**Edit:**
Dropping the `$(CFLAGS)` from line **493** is enough to get it to compile, the following works on msys2:
```
LDFLAGS := $(PLATFORM_LDFLAGS) $(GFX_LDFLAGS)
ifeq ($(COMPILER),gcc)
  LDFLAGS += $(CFLAGS)
endif
```
**End of edit**

Last few lines for context:

```
echo >> build/us_pc/textures/intro_raw/white_star_5.rgba16.inc.c
echo >> build/us_pc/textures/intro_raw/white_star_7.rgba16.inc.c
echo >> build/us_pc/textures/intro_raw/white_star_6.rgba16.inc.c
hexdump -v -e '1/1 "0x%X,"' build/us_pc/sound/sound_data.ctl > build/us_pc/sound/sound_data.ctl.inc.c
python3 tools/assemble_sound.py --sequences build/us_pc/sound/sequences.bin build/us_pc/sound/bank_sets sound/sound_banks/ sound/sequences.json sound/sequences/us/01_cutscene_collect_star.m64 soun/sequences/us/02_menu_title_screen.m64 sound/sequences/us/03_level_grass.m64 sound/sequences/us/04_level_inside_castle.m64 sound/sequences/us/05_level_water.m64 sound/sequences/us/06_level_hot.m64sound/sequences/us/07_level_boss_koopa.m64 sound/sequences/us/08_level_snow.m64 sound/sequences/us/09_level_slide.m64 sound/sequences/us/0A_level_spooky.m64 sound/sequences/us/0B_event_piranha_plat.m64 sound/sequences/us/0C_level_underground.m64 sound/sequences/us/0D_menu_star_select.m64 sound/sequences/us/0E_event_powerup.m64 sound/sequences/us/0F_event_metal_cap.m64 sound/sequences/us/10event_koopa_message.m64 sound/sequences/us/11_level_koopa_road.m64 sound/sequences/us/12_event_high_score.m64 sound/sequences/us/13_event_merry_go_round.m64 sound/sequences/us/14_event_race.m64 sond/sequences/us/15_cutscene_star_spawn.m64 sound/sequences/us/16_event_boss.m64 sound/sequences/us/17_cutscene_collect_key.m64 sound/sequences/us/18_event_endless_stairs.m64 sound/sequences/us/19_evel_boss_koopa_final.m64 sound/sequences/us/1A_cutscene_credits.m64 sound/sequences/us/1B_event_solve_puzzle.m64 sound/sequences/us/1C_event_toad_message.m64 sound/sequences/us/1D_event_peach_mesage.m64 sound/sequences/us/1E_cutscene_intro.m64 sound/sequences/us/1F_cutscene_victory.m64 sound/sequences/us/20_cutscene_ending.m64 sound/sequences/us/21_menu_file_select.m64 sound/sequences/us/2_cutscene_lakitu.m64   build/us_pc/sound/sequences/00_sound_player.m64 -DVERSION_US $(cat build/us_pc/endian-and-bitwidth)
hexdump -v -e '1/1 "0x%X,"' build/us_pc/sound/sound_data.tbl > build/us_pc/sound/sound_data.tbl.inc.c
echo >> build/us_pc/sound/sound_data.ctl.inc.c
gcc -c -Ofast -flto=auto -fno-fat-lto-objects -fuse-linker-plugin -pipe -I include -I build/us_pc -I build/us_pc/include -I src -I . -D_LANGUAGE_C -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WNDOWS -DNO_SEGMENTED_MEMORY -DENABLE_DX11 -DWIDESCREEN -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -march=native -o build/us_pc/src/goddard/renderer.o src/goddard/renderer.c
hexdump -v -e '1/1 "0x%X,"' build/us_pc/sound/sequences.bin > build/us_pc/sound/sequences.bin.inc.c
hexdump -v -e '1/1 "0x%X,"' build/us_pc/sound/bank_sets > build/us_pc/sound/bank_sets.inc.c
echo >> build/us_pc/sound/bank_sets.inc.c
echo >> build/us_pc/sound/sequences.bin.inc.c
echo >> build/us_pc/sound/sound_data.tbl.inc.c
gcc -c -Ofast -flto=auto -fno-fat-lto-objects -fuse-linker-plugin -pipe -I include -I build/us_pc -I build/us_pc/include -I src -I . -D_LANGUAGE_C -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WNDOWS -DNO_SEGMENTED_MEMORY -DENABLE_DX11 -DWIDESCREEN -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -march=native -o build/us_pc/sound/sound_data.o sound/sound_data.c
g++ -L build/us_pc -o build/us_pc/sm64.us.f3dex2e.exe build/us_pc/src/engine/behavior_script.o build/us_pc/src/engine/geo_layout.o build/us_pc/src/engine/graph_node.o build/us_pc/src/engine/graph_ode_manager.o build/us_pc/src/engine/level_script.o build/us_pc/src/engine/math_util.o build/us_pc/src/engine/surface_collision.o build/us_pc/src/engine/surface_load.o build/us_pc/src/game/area.o uild/us_pc/src/game/behavior_actions.o build/us_pc/src/game/camera.o build/us_pc/src/game/crash_screen.o build/us_pc/src/game/debug.o build/us_pc/src/game/debug_course.o build/us_pc/src/game/envfxbubbles.o build/us_pc/src/game/envfx_snow.o build/us_pc/src/game/game_init.o build/us_pc/src/game/geo_misc.o build/us_pc/src/game/hud.o build/us_pc/src/game/ingame_menu.o build/us_pc/src/game/inteaction.o build/us_pc/src/game/level_geo.o build/us_pc/src/game/level_update.o build/us_pc/src/game/macro_special_objects.o build/us_pc/src/game/mario.o build/us_pc/src/game/mario_actions_airborne. build/us_pc/src/game/mario_actions_automatic.o build/us_pc/src/game/mario_actions_cutscene.o build/us_pc/src/game/mario_actions_moving.o build/us_pc/src/game/mario_actions_object.o build/us_pc/sr/game/mario_actions_stationary.o build/us_pc/src/game/mario_actions_submerged.o build/us_pc/src/game/mario_misc.o build/us_pc/src/game/mario_step.o build/us_pc/src/game/memory.o build/us_pc/src/gae/moving_texture.o build/us_pc/src/game/obj_behaviors.o build/us_pc/src/game/obj_behaviors_2.o build/us_pc/src/game/object_collision.o build/us_pc/src/game/object_helpers.o build/us_pc/src/game/obect_list_processor.o build/us_pc/src/game/paintings.o build/us_pc/src/game/platform_displacement.o build/us_pc/src/game/print.o build/us_pc/src/game/profiler.o build/us_pc/src/game/rendering_graphnode.o build/us_pc/src/game/save_file.o build/us_pc/src/game/screen_transition.o build/us_pc/src/game/shadow.o build/us_pc/src/game/skybox.o build/us_pc/src/game/sound_init.o build/us_pc/src/game/pawn_object.o build/us_pc/src/game/spawn_sound.o build/us_pc/src/game/thread6.o build/us_pc/src/audio/data.o build/us_pc/src/audio/effects.o build/us_pc/src/audio/external.o build/us_pc/src/audio/lobals_start.o build/us_pc/src/audio/heap.o build/us_pc/src/audio/load.o build/us_pc/src/audio/playback.o build/us_pc/src/audio/port_eu.o build/us_pc/src/audio/seqplayer.o build/us_pc/src/audio/sythesis.o build/us_pc/src/menu/file_select.o build/us_pc/src/menu/intro_geo.o build/us_pc/src/menu/level_select_menu.o build/us_pc/src/menu/star_select.o build/us_pc/src/buffers/buffers.o build/us_c/src/buffers/framebuffers.o build/us_pc/src/buffers/gfx_output_buffer.o build/us_pc/src/buffers/zbuffer.o build/us_pc/actors/common0.o build/us_pc/actors/common0_geo.o build/us_pc/actors/common1. build/us_pc/actors/common1_geo.o build/us_pc/actors/group0.o build/us_pc/actors/group0_geo.o build/us_pc/actors/group1.o build/us_pc/actors/group1_geo.o build/us_pc/actors/group10.o build/us_pc/ators/group10_geo.o build/us_pc/actors/group11.o build/us_pc/actors/group11_geo.o build/us_pc/actors/group12.o build/us_pc/actors/group12_geo.o build/us_pc/actors/group13.o build/us_pc/actors/group3_geo.o build/us_pc/actors/group14.o build/us_pc/actors/group14_geo.o build/us_pc/actors/group15.o build/us_pc/actors/group15_geo.o build/us_pc/actors/group16.o build/us_pc/actors/group16_geo.o buld/us_pc/actors/group17.o build/us_pc/actors/group17_geo.o build/us_pc/actors/group2.o build/us_pc/actors/group2_geo.o build/us_pc/actors/group3.o build/us_pc/actors/group3_geo.o build/us_pc/actor/group4.o build/us_pc/actors/group4_geo.o build/us_pc/actors/group5.o build/us_pc/actors/group5_geo.o build/us_pc/actors/group6.o build/us_pc/actors/group6_geo.o build/us_pc/actors/group7.o build/s_pc/actors/group7_geo.o build/us_pc/actors/group8.o build/us_pc/actors/group8_geo.o build/us_pc/actors/group9.o build/us_pc/actors/group9_geo.o build/us_pc/levels/entry.o build/us_pc/levels/scrips.o build/us_pc/bin/cave.o build/us_pc/bin/debug_level_select.o build/us_pc/bin/effect.o build/us_pc/bin/fire.o build/us_pc/bin/generic.o build/us_pc/bin/grass.o build/us_pc/bin/inside.o build/us_c/bin/machine.o build/us_pc/bin/mountain.o build/us_pc/bin/outside.o build/us_pc/bin/segment2.o build/us_pc/bin/sky.o build/us_pc/bin/snow.o build/us_pc/bin/spooky.o build/us_pc/bin/title_screen_b.o build/us_pc/bin/water.o build/us_pc/data/behavior_data.o build/us_pc/src/pc/configfile.o build/us_pc/src/pc/mixer.o build/us_pc/src/pc/pc_main.o build/us_pc/src/pc/ultra_reimplementation.o buil/us_pc/src/pc/gfx/gfx_cc.o build/us_pc/src/pc/gfx/gfx_glx.o build/us_pc/src/pc/gfx/gfx_opengl.o build/us_pc/src/pc/gfx/gfx_pc.o build/us_pc/src/pc/gfx/gfx_sdl2.o build/us_pc/src/pc/audio/audio_als.o build/us_pc/src/pc/audio/audio_null.o build/us_pc/src/pc/audio/audio_pulse.o build/us_pc/src/pc/audio/audio_sdl.o build/us_pc/src/pc/controller/controller_emscripten_keyboard.o build/us_pc/src/c/controller/controller_entry_point.o build/us_pc/src/pc/controller/controller_keyboard.o build/us_pc/src/pc/controller/controller_recorded_tas.o build/us_pc/src/pc/controller/controller_sdl.o buid/us_pc/src/pc/controller/controller_wup.o build/us_pc/src/pc/controller/controller_xinput.o build/us_pc/src/pc/controller/wup.o build/us_pc/levels/bbh/leveldata.o build/us_pc/levels/bitdw/leveldaa.o build/us_pc/levels/bitfs/leveldata.o build/us_pc/levels/bits/leveldata.o build/us_pc/levels/bob/leveldata.o build/us_pc/levels/bowser_1/leveldata.o build/us_pc/levels/bowser_2/leveldata.o buil/us_pc/levels/bowser_3/leveldata.o build/us_pc/levels/castle_courtyard/leveldata.o build/us_pc/levels/castle_grounds/leveldata.o build/us_pc/levels/castle_inside/leveldata.o build/us_pc/levels/ccmleveldata.o build/us_pc/levels/cotmc/leveldata.o build/us_pc/levels/ddd/leveldata.o build/us_pc/levels/ending/leveldata.o build/us_pc/levels/hmc/leveldata.o build/us_pc/levels/intro/leveldata.o buld/us_pc/levels/jrb/leveldata.o build/us_pc/levels/lll/leveldata.o build/us_pc/levels/menu/leveldata.o build/us_pc/levels/pss/leveldata.o build/us_pc/levels/rr/leveldata.o build/us_pc/levels/sa/leeldata.o build/us_pc/levels/sl/leveldata.o build/us_pc/levels/ssl/leveldata.o build/us_pc/levels/thi/leveldata.o build/us_pc/levels/totwc/leveldata.o build/us_pc/levels/ttc/leveldata.o build/us_pclevels/ttm/leveldata.o build/us_pc/levels/vcutm/leveldata.o build/us_pc/levels/wdw/leveldata.o build/us_pc/levels/wf/leveldata.o build/us_pc/levels/wmotr/leveldata.o build/us_pc/levels/bbh/script. build/us_pc/levels/bitdw/script.o build/us_pc/levels/bitfs/script.o build/us_pc/levels/bits/script.o build/us_pc/levels/bob/script.o build/us_pc/levels/bowser_1/script.o build/us_pc/levels/bowser2/script.o build/us_pc/levels/bowser_3/script.o build/us_pc/levels/castle_courtyard/script.o build/us_pc/levels/castle_grounds/script.o build/us_pc/levels/castle_inside/script.o build/us_pc/levelsccm/script.o build/us_pc/levels/cotmc/script.o build/us_pc/levels/ddd/script.o build/us_pc/levels/ending/script.o build/us_pc/levels/hmc/script.o build/us_pc/levels/intro/script.o build/us_pc/leves/jrb/script.o build/us_pc/levels/lll/script.o build/us_pc/levels/menu/script.o build/us_pc/levels/pss/script.o build/us_pc/levels/rr/script.o build/us_pc/levels/sa/script.o build/us_pc/levels/sl/cript.o build/us_pc/levels/ssl/script.o build/us_pc/levels/thi/script.o build/us_pc/levels/totwc/script.o build/us_pc/levels/ttc/script.o build/us_pc/levels/ttm/script.o build/us_pc/levels/vcutm/sript.o build/us_pc/levels/wdw/script.o build/us_pc/levels/wf/script.o build/us_pc/levels/wmotr/script.o build/us_pc/levels/bbh/geo.o build/us_pc/levels/bitdw/geo.o build/us_pc/levels/bitfs/geo.o bild/us_pc/levels/bits/geo.o build/us_pc/levels/bob/geo.o build/us_pc/levels/bowser_1/geo.o build/us_pc/levels/bowser_2/geo.o build/us_pc/levels/bowser_3/geo.o build/us_pc/levels/castle_courtyard/go.o build/us_pc/levels/castle_grounds/geo.o build/us_pc/levels/castle_inside/geo.o build/us_pc/levels/ccm/geo.o build/us_pc/levels/cotmc/geo.o build/us_pc/levels/ddd/geo.o build/us_pc/levels/endin/geo.o build/us_pc/levels/hmc/geo.o build/us_pc/levels/intro/geo.o build/us_pc/levels/jrb/geo.o build/us_pc/levels/lll/geo.o build/us_pc/levels/menu/geo.o build/us_pc/levels/pss/geo.o build/us_pc/evels/rr/geo.o build/us_pc/levels/sa/geo.o build/us_pc/levels/sl/geo.o build/us_pc/levels/ssl/geo.o build/us_pc/levels/thi/geo.o build/us_pc/levels/totwc/geo.o build/us_pc/levels/ttc/geo.o build/u_pc/levels/ttm/geo.o build/us_pc/levels/vcutm/geo.o build/us_pc/levels/wdw/geo.o build/us_pc/levels/wf/geo.o build/us_pc/levels/wmotr/geo.o build/us_pc/src/pc/gfx/gfx_direct3d_common.o build/us_pcsrc/pc/gfx/gfx_direct3d11.o build/us_pc/src/pc/gfx/gfx_direct3d12.o build/us_pc/src/pc/gfx/gfx_dxgi.o build/us_pc/src/pc/audio/audio_wasapi.o  build/us_pc/assets/mario_anim_data.o build/us_pc/asses/demo_data.o build/us_pc/bin/bbh_skybox.o build/us_pc/bin/bidw_skybox.o build/us_pc/bin/bitfs_skybox.o build/us_pc/bin/bits_skybox.o build/us_pc/bin/ccm_skybox.o build/us_pc/bin/cloud_floor_skybo.o build/us_pc/bin/clouds_skybox.o build/us_pc/bin/ssl_skybox.o build/us_pc/bin/water_skybox.o build/us_pc/bin/wdw_skybox.o build/us_pc/sound/sound_data.o  build/us_pc/lib/src/alBnkfNew.o build/uspc/lib/src/guLookAtRef.o build/us_pc/lib/src/guMtxF2L.o build/us_pc/lib/src/guNormalize.o build/us_pc/lib/src/guOrthoF.o build/us_pc/lib/src/guPerspectiveF.o build/us_pc/lib/src/guRotateF.o build/s_pc/lib/src/guScaleF.o build/us_pc/lib/src/guTranslateF.o build/us_pc/src/goddard/debug_utils.o build/us_pc/src/goddard/draw_objects.o build/us_pc/src/goddard/dynlist_proc.o build/us_pc/src/goddad/gd_main.o build/us_pc/src/goddard/gd_math.o build/us_pc/src/goddard/gd_memory.o build/us_pc/src/goddard/joints.o build/us_pc/src/goddard/objects.o build/us_pc/src/goddard/old_menu.o build/us_pc/rc/goddard/particles.o build/us_pc/src/goddard/renderer.o build/us_pc/src/goddard/sfx.o build/us_pc/src/goddard/shape_helper.o build/us_pc/src/goddard/skin.o build/us_pc/src/goddard/skin_movement. build/us_pc/src/goddard/dynlists/anim_group_1.o build/us_pc/src/goddard/dynlists/anim_group_2.o build/us_pc/src/goddard/dynlists/anim_mario_eyebrows_1.o build/us_pc/src/goddard/dynlists/anim_mari_lips_1.o build/us_pc/src/goddard/dynlists/anim_mario_lips_2.o build/us_pc/src/goddard/dynlists/anim_mario_mustache_left.o build/us_pc/src/goddard/dynlists/anim_mario_mustache_right.o build/us_pc/rc/goddard/dynlists/dynlist_mario_face.o build/us_pc/src/goddard/dynlists/dynlist_mario_master.o build/us_pc/src/goddard/dynlists/dynlist_test_cube.o build/us_pc/src/goddard/dynlists/dynlist_unuse.o build/us_pc/src/goddard/dynlists/dynlists_mario_eyebrows_mustache.o build/us_pc/src/goddard/dynlists/dynlists_mario_eyes.o -lm -lxinput9_1_0 -lole32 -no-pie -mwindows -lgdi32 -static  -Ofast -fto=auto -fno-fat-lto-objects -fuse-linker-plugin -pipe -I include -I build/us_pc -I build/us_pc/include -I src -I . -D_LANGUAGE_C -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WINDOWS -DNO_SEGMETED_MEMORY -DENABLE_DX11 -DWIDESCREEN -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -march=native
src/game/segment7.h:27:13: warning: type of 'intro_seg7_dl_0700B3A0' does not match original declaration [-Wlto-type-mismatch]
   27 | extern Gfx *intro_seg7_dl_0700B3A0;
      |             ^
levels/intro/leveldata.c:3304:11: note: 'intro_seg7_dl_0700B3A0' was previously declared here
 3304 | const Gfx intro_seg7_dl_0700B3A0[] = {
      |           ^
src/game/segment7.h:28:13: warning: type of 'intro_seg7_dl_0700C6A0' does not match original declaration [-Wlto-type-mismatch]
   28 | extern Gfx *intro_seg7_dl_0700C6A0;
      |             ^
levels/intro/leveldata.c:3363:11: note: 'intro_seg7_dl_0700C6A0' was previously declared here
 3363 | const Gfx intro_seg7_dl_0700C6A0[] = {
      |           ^
src/game/obj_behaviors.c:72:14: warning: type of 'inside_castle_seg7_trajectory_mips' does not match original declaration [-Wlto-type-mismatch]
   72 | extern void *inside_castle_seg7_trajectory_mips;
      |              ^
./levels/castle_inside/areas/3/trajectory.inc.c:93:25: note: 'inside_castle_seg7_trajectory_mips' was previously declared here
   93 | const Trajectory *const inside_castle_seg7_trajectory_mips[] = {
      |                         ^
src/game/obj_behaviors.c:71:14: warning: type of 'ccm_seg7_trajectory_snowman' does not match original declaration [-Wlto-type-mismatch]
   71 | extern void *ccm_seg7_trajectory_snowman;
      |              ^
./levels/ccm/areas/1/trajectory.inc.c:2:18: note: 'ccm_seg7_trajectory_snowman' was previously declared here
    2 | const Trajectory ccm_seg7_trajectory_snowman[] = {
      |                  ^
src/game/geo_misc.c:31:18: warning: type of 'flying_carpet_static_vertex_data' does not match original declaration [-Wlto-type-mismatch]
   31 | extern const s16 flying_carpet_static_vertex_data[NUM_FLYING_CARPET_VERTICES];
      |                  ^
./levels/rr/flying_carpet/model.inc.c:10:11: note: array types have different bounds
   10 | const s16 flying_carpet_static_vertex_data[] = {
      |           ^
./levels/rr/flying_carpet/model.inc.c:10:11: note: 'flying_carpet_static_vertex_data' was previously declared here
src/game/envfx_snow.c:55:14: warning: type of 'tiny_bubble_dl_0B006CD8' does not match original declaration [-Wlto-type-mismatch]
   55 | extern void *tiny_bubble_dl_0B006CD8;
      |              ^
bin/effect.c:142:11: note: 'tiny_bubble_dl_0B006CD8' was previously declared here
  142 | const Gfx tiny_bubble_dl_0B006CD8[] = {
      |           ^
src/game/envfx_snow.c:54:14: warning: type of 'tiny_bubble_dl_0B006A50' does not match original declaration [-Wlto-type-mismatch]
   54 | extern void *tiny_bubble_dl_0B006A50;
      |              ^
bin/effect.c:112:11: note: 'tiny_bubble_dl_0B006A50' was previously declared here
  112 | const Gfx tiny_bubble_dl_0B006A50[] = {
      |           ^
src/game/envfx_snow.c:53:14: warning: type of 'tiny_bubble_dl_0B006AB0' does not match original declaration [-Wlto-type-mismatch]
   53 | extern void *tiny_bubble_dl_0B006AB0;
      |              ^
bin/effect.c:128:11: note: 'tiny_bubble_dl_0B006AB0' was previously declared here
  128 | const Gfx tiny_bubble_dl_0B006AB0[] = {
      |           ^
make: the '-j' option requires a positive integer argument
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  -E STRING, --eval=STRING    Evaluate STRING as a makefile statement.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from recipes.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no recipe; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo recipes.
  --no-silent                 Echo recipes (disable --silent mode).
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  --trace                     Print tracing information.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.

This program built for x86_64-pc-msys
Report bugs to <bug-make@gnu.org>
lto-wrapper.exe: fatal error: make returned 2 exit status
compilation terminated.
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:821: build/us_pc/sm64.us.f3dex2e.exe] Error 1
```

**Comment by V10lator** [comment]
Thanks for this. The issue is `make: the '-j' option requires a positive integer argument`. Now I guess you didn't specify a negative argument or 0 ? Somebody reported the same on the Wii U port but it compiles fine in WSL (which is the currently recommended way for Wii U development vause of many hiccups with MSYS2), so I guess it's some devkitPro issue in combination with MSYS2 but that needs more research.

//EDIT: Great finding. :) Could you show me line 493 at your Makefile? Mine is `CPP := cpp -P` ...?

//EDIT²: Looked at the wrong Makefile, sry. Anyway: Your workaround removes LTO as COMPILER is never gcc (it's setted to ido and never changed in the Makefile. Is that another bug?)

**Comment by mkst** [comment]
I'm doing `make -j4` which works with master, but chokes on this PR.

re: "COMPILER is always ido" - ah ok, that just means that my `ifeq` condition will never get triggered, so is the wrong condition to be checking for... I guess you could base it on one of the [msys2](https://www.msys2.org/wiki/Porting/) vars being defined?

This is ~~untested~~ tested and works when compiling under msys2 (i.e. dont add the flags to the linker):
```
LDFLAGS := $(PLATFORM_LDFLAGS) $(GFX_LDFLAGS)
ifndef __MSYS2__
  LDFLAGS += $(CFLAGS)
endif
```

this is a bit of a hack as it doesn't address the underlying issue of 'what is the msys2 linker crying about', but I don't have the time/energy to look into that.

**Comment by V10lator** [comment]
While this might work AFAIK you need to add the CFLAGS to the LDFLAGS for LTO to work. So I'll setup a msys2 environments the next days to try to find and fix the real root of this issue.

Please don't merge this as long as the issue hasn't been resolved.

**Comment by MegaMech** [comment]
This PR is considered abandoned.

**Pull request closed without merging**
